apiVersion: v1
kind: Service

metadata:
  name: load-balancer-hello
  namespace: devops
  
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
